# Порт http сервера
server:
  port: ${SERVICE_PORT:8080}

service:
  inbound:
    username: user
    useradd: "1"
  externalEndpoint:
    url: "http://webservices.oorsprong.org/websamples.countryinfo/CountryInfoService.wso"

spring:
  application:
        name: 'demoCamelPOJOToSOAP'

camel:
  springboot:
          name: "MyCamel"
          main-run-controller: true

logging:
   level:
     root: INFO

hawtio:
  authenticationEnabled: false